<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.21">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ketil B., Laurits H., Herman E. og Theodor S.">
<meta name="dcterms.date" content="2025-10-30">

<title>Arbeidskrav 3: Statistisk analyse av Openpowerlifting datasettet</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Arbeidskrav3_files/libs/clipboard/clipboard.min.js"></script>
<script src="Arbeidskrav3_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Arbeidskrav3_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Arbeidskrav3_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="Arbeidskrav3_files/libs/quarto-html/popper.min.js"></script>
<script src="Arbeidskrav3_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Arbeidskrav3_files/libs/quarto-html/anchor.min.js"></script>
<link href="Arbeidskrav3_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Arbeidskrav3_files/libs/quarto-html/quarto-syntax-highlighting-ea1d7ac60288e0f1efdbc993fd8432ae.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Arbeidskrav3_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Arbeidskrav3_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Arbeidskrav3_files/libs/bootstrap/bootstrap-9e3ffae467580fdb927a41352e75a2e0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Innhold</h2>
   
  <ul>
  <li><a href="#beskrive-sammenhenger" id="toc-beskrive-sammenhenger" class="nav-link active" data-scroll-target="#beskrive-sammenhenger"><span class="header-section-number">1</span> Beskrive sammenhenger</a>
  <ul class="collapse">
  <li><a href="#sammenhengen-mellom-to-kontinuerlige-variabler-total-og-kroppsvekt" id="toc-sammenhengen-mellom-to-kontinuerlige-variabler-total-og-kroppsvekt" class="nav-link" data-scroll-target="#sammenhengen-mellom-to-kontinuerlige-variabler-total-og-kroppsvekt"><span class="header-section-number">1.1</span> Sammenhengen mellom to kontinuerlige variabler (Total og kroppsvekt)</a></li>
  <li><a href="#sammenhengen-mellom-total-kjønn-og-alder" id="toc-sammenhengen-mellom-total-kjønn-og-alder" class="nav-link" data-scroll-target="#sammenhengen-mellom-total-kjønn-og-alder"><span class="header-section-number">1.2</span> Sammenhengen mellom total, kjønn og alder</a>
  <ul class="collapse">
  <li><a href="#tolkning-av-regresjonsmodellen" id="toc-tolkning-av-regresjonsmodellen" class="nav-link" data-scroll-target="#tolkning-av-regresjonsmodellen"><span class="header-section-number">1.2.1</span> Tolkning av regresjonsmodellen</a></li>
  <li><a href="#graf-2-kurvilineær-graf-av-sammenhengen-mellom-total-kjønn-og-alder" id="toc-graf-2-kurvilineær-graf-av-sammenhengen-mellom-total-kjønn-og-alder" class="nav-link" data-scroll-target="#graf-2-kurvilineær-graf-av-sammenhengen-mellom-total-kjønn-og-alder"><span class="header-section-number">1.2.2</span> Graf 2: Kurvilineær graf av sammenhengen mellom total, kjønn og alder</a></li>
  </ul></li>
  <li><a href="#hvordan-kan-vi-tolke-estimatet-i-en-generalisert-lineær-modell-hvor-den-avhengige-variabelen-er-enten-1-eller-0-hva-betyr-link-function-i-denne-sammenhengen-og-hva-gjør-den" id="toc-hvordan-kan-vi-tolke-estimatet-i-en-generalisert-lineær-modell-hvor-den-avhengige-variabelen-er-enten-1-eller-0-hva-betyr-link-function-i-denne-sammenhengen-og-hva-gjør-den" class="nav-link" data-scroll-target="#hvordan-kan-vi-tolke-estimatet-i-en-generalisert-lineær-modell-hvor-den-avhengige-variabelen-er-enten-1-eller-0-hva-betyr-link-function-i-denne-sammenhengen-og-hva-gjør-den"><span class="header-section-number">1.3</span> Hvordan kan vi tolke estimatet i en generalisert lineær modell hvor den avhengige variabelen er enten 1 eller 0? Hva betyr «link-function» i denne sammenhengen og hva gjør den?</a></li>
  </ul></li>
  <li><a href="#predikere-observasjoner" id="toc-predikere-observasjoner" class="nav-link" data-scroll-target="#predikere-observasjoner"><span class="header-section-number">2</span> Predikere observasjoner</a>
  <ul class="collapse">
  <li><a href="#bruk-data-fra-datasettet-strengthvolume-og-lag-en-prediksjonsmodell-for-legext-basert-på-legpress." id="toc-bruk-data-fra-datasettet-strengthvolume-og-lag-en-prediksjonsmodell-for-legext-basert-på-legpress." class="nav-link" data-scroll-target="#bruk-data-fra-datasettet-strengthvolume-og-lag-en-prediksjonsmodell-for-legext-basert-på-legpress."><span class="header-section-number">2.0.1</span> Bruk data fra datasettet strengthvolume og lag en prediksjonsmodell for legext basert på legpress.</a></li>
  <li><a href="#bruk-data-fra-et-tidspunkt-time-og-et-treningsvolum-sets" id="toc-bruk-data-fra-et-tidspunkt-time-og-et-treningsvolum-sets" class="nav-link" data-scroll-target="#bruk-data-fra-et-tidspunkt-time-og-et-treningsvolum-sets"><span class="header-section-number">2.1</span> Bruk data fra et tidspunkt (time) og et treningsvolum (sets)</a>
  <ul class="collapse">
  <li><a href="#hvordan-spiller-kjønn-sex-inn-på-prediksjonen-hvordan-kan-du-bruke-kjønn-for-å-si-noe-om-prediksjoner-innad-kjønn-og-i-gjennomsnitt-i-begge-kjønn" id="toc-hvordan-spiller-kjønn-sex-inn-på-prediksjonen-hvordan-kan-du-bruke-kjønn-for-å-si-noe-om-prediksjoner-innad-kjønn-og-i-gjennomsnitt-i-begge-kjønn" class="nav-link" data-scroll-target="#hvordan-spiller-kjønn-sex-inn-på-prediksjonen-hvordan-kan-du-bruke-kjønn-for-å-si-noe-om-prediksjoner-innad-kjønn-og-i-gjennomsnitt-i-begge-kjønn"><span class="header-section-number">2.1.1</span> Hvordan spiller kjønn (sex) inn på prediksjonen, hvordan kan du bruke kjønn for å si noe om prediksjoner innad kjønn og i gjennomsnitt i begge kjønn?</a></li>
  <li><a href="#modellen-gir-deg-et-estimat-men-for-en-gitt-verdi-på-legpress-hva-sier-modellen-om-i-hvilket-område-vi-kan-forvente-å-finne-nye-observasjoner" id="toc-modellen-gir-deg-et-estimat-men-for-en-gitt-verdi-på-legpress-hva-sier-modellen-om-i-hvilket-område-vi-kan-forvente-å-finne-nye-observasjoner" class="nav-link" data-scroll-target="#modellen-gir-deg-et-estimat-men-for-en-gitt-verdi-på-legpress-hva-sier-modellen-om-i-hvilket-område-vi-kan-forvente-å-finne-nye-observasjoner"><span class="header-section-number">2.1.2</span> Modellen gir deg et estimat, men for en gitt verdi på legpress, hva sier modellen om i hvilket område vi kan forvente å finne nye observasjoner?</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#trekke-slutninger" id="toc-trekke-slutninger" class="nav-link" data-scroll-target="#trekke-slutninger"><span class="header-section-number">3</span> Trekke slutninger</a>
  <ul class="collapse">
  <li><a href="#bruk-datasettet-strengtvolume-og-formuler-en-modell-som-gir-oss-et-estimat-på-forskjell-i-gjennomsnitt-mellom-sets-i-forandring-fra-tidspunkt-pre-til-tidspunkt-post-i-legext.-gi-begrunnelse-til-valg-av-modell-og-håndtering-av-data." id="toc-bruk-datasettet-strengtvolume-og-formuler-en-modell-som-gir-oss-et-estimat-på-forskjell-i-gjennomsnitt-mellom-sets-i-forandring-fra-tidspunkt-pre-til-tidspunkt-post-i-legext.-gi-begrunnelse-til-valg-av-modell-og-håndtering-av-data." class="nav-link" data-scroll-target="#bruk-datasettet-strengtvolume-og-formuler-en-modell-som-gir-oss-et-estimat-på-forskjell-i-gjennomsnitt-mellom-sets-i-forandring-fra-tidspunkt-pre-til-tidspunkt-post-i-legext.-gi-begrunnelse-til-valg-av-modell-og-håndtering-av-data."><span class="header-section-number">3.1</span> Bruk datasettet strengtvolume og formuler en modell som gir oss et estimat på forskjell i gjennomsnitt mellom sets i forandring fra tidspunkt pre til tidspunkt post i legext. Gi begrunnelse til valg av modell og håndtering av data.</a>
  <ul class="collapse">
  <li><a href="#hvordan-kan-vi-bruke-regresjonsmodellen-for-å-si-noe-om-populasjonen-som-dataene-kommer-fra" id="toc-hvordan-kan-vi-bruke-regresjonsmodellen-for-å-si-noe-om-populasjonen-som-dataene-kommer-fra" class="nav-link" data-scroll-target="#hvordan-kan-vi-bruke-regresjonsmodellen-for-å-si-noe-om-populasjonen-som-dataene-kommer-fra"><span class="header-section-number">3.1.1</span> Hvordan kan vi bruke regresjonsmodellen for å si noe om populasjonen som dataene kommer fra?</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Arbeidskrav 3: Statistisk analyse av Openpowerlifting datasettet</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Ketil B., Laurits H., Herman E. og Theodor S. </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 30, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="beskrive-sammenhenger" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Beskrive sammenhenger</h1>
<p>Første del av arbeidskravet tar utgangspunkt i “Openpowerlifting” datasettet.</p>
<p>Begreper som brukes videre i denne analysen:</p>
<p><strong>Total</strong><em>: Summen av beste løftet i knebøy, benkpress og markløft sammenlagt, uttrykt i antall kilogram (eksempel: 150kg knebøy, 100 kg benkpress, 200 kg markløft = total på 450 kg)</em></p>
<p><strong>Maksimalstyrke</strong>: Brukes synonymt med total i denne analysen</p>
<p><strong>Utstyrsfritt</strong>: Det innebærer at man kun kan bruke et enkelt lag løftebelte (10 - 13mm bredde), myke knevarmere, håndleddsstøtter og drakt uten støtte. Alt annet utstyr er ikke tillatt.</p>
<section id="sammenhengen-mellom-to-kontinuerlige-variabler-total-og-kroppsvekt" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="sammenhengen-mellom-to-kontinuerlige-variabler-total-og-kroppsvekt"><span class="header-section-number">1.1</span> Sammenhengen mellom to kontinuerlige variabler (Total og kroppsvekt)</h2>
<p>Sammenhengen mellom to kontinuerlige variabler kan beskrives ved hjelp av korrelasjon og lineær regresjon. Korrelasjonskoeffisienten (r) viser styrken og retningen på den sammenhengen mellom de to variablene, og varierer mellom -1 og 1. I dette tilfellet er korrelasjonen mellom kroppsvekt og total løftet mengde r=0.369r, noe som indikerer en moderat positiv sammenheng. Løftere med høyere kroppsvekt har en tendens til å løfte mer totalt.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  sample.powerlifting$TotalKg and sample.powerlifting$BodyweightKg
t = 25.48, df = 4998, p-value &lt; 2.2e-16
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.3143008 0.3633702
sample estimates:
      cor 
0.3390661 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = TotalKg ~ BodyweightKg, data = sample.powerlifting)

Residuals:
    Min      1Q  Median      3Q     Max 
-492.42 -178.23    5.51  156.56  542.93 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   85.7888    10.5539   8.129 5.43e-16 ***
BodyweightKg   3.0933     0.1214  25.480  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 186.7 on 4998 degrees of freedom
Multiple R-squared:  0.115, Adjusted R-squared:  0.1148 
F-statistic: 649.2 on 1 and 4998 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Arbeidskrav3_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>I en lineær regresjonsmodell gir i tillegg et mål på hvor mye den avhengige variabelen (TotalKg) endrer seg når den uavhengige variabelen (BodyweightKg) øker.</p>
<p>I modellen TotalKg = 79.93 + 3.35 × BodyweightKg betyr dette at totalen i gjennomsnitt øker med omtrent 3.35 kg for hver ekstra kilo kroppsvekt.</p>
<p>Det finnes en direkte kobling mellom korrelasjonskoeffisienten og regresjonsmodellen: b1=r×(sy/sx), der s(y) og s(x) ​er standardavvikene til henholdsvis TotalKg og BodyweightKg. Når vi beregner denne forventede stigningstallet ut fra korrelasjonen, får vi nøyaktig samme verdi som i regresjonsmodellen (b_expected = 3,35). Dette viser at analysen er konsistent, og at korrelasjon og regresjon beskriver den samme lineære sammenhengen. Samlet viser analysen en signifikant, men moderat lineær sammenheng mellom kroppsvekt og total løfteprestasjon.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate correlation between bodyweight and total lift</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>r <span class="ot">&lt;-</span> <span class="fu">cor</span>(sample.powerlifting<span class="sc">$</span>BodyweightKg, sample.powerlifting<span class="sc">$</span>TotalKg)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate standard deviations of both variables</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>sd_y <span class="ot">&lt;-</span> <span class="fu">sd</span>(sample.powerlifting<span class="sc">$</span>TotalKg)       <span class="co"># standard deviation of Total (Y)</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>sd_x <span class="ot">&lt;-</span> <span class="fu">sd</span>(sample.powerlifting<span class="sc">$</span>BodyweightKg)  <span class="co"># standard deviation of Bodyweight (X)</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute the expected slope (b) from the correlation</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>b_expected <span class="ot">&lt;-</span> r <span class="sc">*</span> (sd_y <span class="sc">/</span> sd_x)</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the expected regression coefficient</span></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>b_expected</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.093326</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>mean_x <span class="ot">&lt;-</span> <span class="fu">mean</span>(sample.powerlifting<span class="sc">$</span>BodyweightKg)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>mean_y <span class="ot">&lt;-</span> <span class="fu">mean</span>(sample.powerlifting<span class="sc">$</span>TotalKg)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>b0_expected <span class="ot">&lt;-</span> mean_y <span class="sc">-</span> b_expected <span class="sc">*</span> mean_x</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="sammenhengen-mellom-total-kjønn-og-alder" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="sammenhengen-mellom-total-kjønn-og-alder"><span class="header-section-number">1.2</span> Sammenhengen mellom total, kjønn og alder</h2>
<p>Det er godt etablert at både kjønn og alder har en effekt på maksimalstyrke. Menn løfter i gjennomsnitt med kvinner, og alder kan ha både en negativ og positiv innvirkning på maksimalstyrke.</p>
<p>Fra et fysiologisk standpunkt kan vi anta at det vil være et kurvilineært forhold mellom total, kjønn og alder, ettersom man vil bli sterkere opp til en viss alder, før man senere vil bli svakere igjen. Vi vil også forvente at menn og kvinner vil registrere ulike totaler på bakgrunn av ulik styrke.</p>
<p>Siden “openpowerlifting” datasettet inneholder over tre millioner rader, må vi filtrere dataene slik at de er mer håndterbare å lage modeller og grafer med. Vi valgte dermed å filtrere et utvalg på 5000 observasjoner.</p>
<p>Vi testet både en lineær og en polynomial regresjonsmodell. Det viste seg at den polynomiale modellen var mer passende, ettersom den lineære modellen viste en negativ korrelasjon mellom alder og total, som er fysiologisk svært usannsynlig (en 15-åring ville vært sterkere enn en 25 åring i gjennomsnitt med den lineære modellen). Ved bruk av den polynomiale modellen derimot, ser at vi totalen øker med økende alder til et visst punkt, før den igjen synker, og indikerer at det er et kurvilineært forhold.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Filtrerer datasettet slik at det er mer håndterbart og gjelder en mer homogen målgruppe</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>powerlifting.clean <span class="ot">&lt;-</span> openpowerlifting <span class="sc">|&gt;</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span><span class="fu">is.na</span>(TotalKg),  <span class="co">#Har en registrert total</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>    TotalKg <span class="sc">&gt;</span> <span class="dv">0</span>,</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>    Equipment <span class="sc">==</span> <span class="st">"Raw"</span>, <span class="co">#Utstyrsfritt</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span><span class="fu">is.na</span>(Tested), <span class="co">#Dopingtestet</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>    Sex <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"M"</span>, <span class="st">"F"</span>),<span class="co">#Kun kvinner og menn</span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span><span class="fu">is.na</span>(Dots)</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a><span class="co">#Vi tar et tilfeldig utvalg "powerlifting.clean"</span></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>sample.powerlifting <span class="ot">&lt;-</span> powerlifting.clean <span class="sc">|&gt;</span></span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sample_n</span>(<span class="dv">5000</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Nå som vi har filtrert datasettet, kan vi lage en regresjonsmodell og en graf.</p>
<p><em>Merk: Med denne regresjonsmodellen gjør vi en antagelse at alder har en lik effekt på maksimalstyrke uavhengig av kjønn</em></p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Variabel</th>
<th style="text-align: right;">Estimat</th>
<th style="text-align: left;">p-verdi</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">124.543</td>
<td style="text-align: left;">&lt;0.001</td>
</tr>
<tr class="even">
<td style="text-align: left;">SexM</td>
<td style="text-align: right;">143.822</td>
<td style="text-align: left;">&lt;0.001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Age</td>
<td style="text-align: right;">9.553</td>
<td style="text-align: left;">&lt;0.001</td>
</tr>
<tr class="even">
<td style="text-align: left;">I(Age^2)</td>
<td style="text-align: right;">-0.155</td>
<td style="text-align: left;">&lt;0.001</td>
</tr>
</tbody>
</table>
</div>
</div>
<section id="tolkning-av-regresjonsmodellen" class="level3" data-number="1.2.1">
<h3 data-number="1.2.1" class="anchored" data-anchor-id="tolkning-av-regresjonsmodellen"><span class="header-section-number">1.2.1</span> Tolkning av regresjonsmodellen</h3>
<p>Vi ser fra modellen at skjæringspunktet er 124.5 kg, som betyr at gjennomsnittlig kvinne vil ha en total på 124.5 kg ved en alder av 0. Dette er det matematiske utgangspunktet til modellen, og i praksis ikke nyttig og unøyaktig siden datasettet ikke inneholder data på så unge utøvere. Vi ser også at menn i gjennomsnitt løfter 143.8kg mer enn kvinner, og at for hver økning i alder med antall år, vil vi få en økning på 9.6kg på totalen. Koeffisienten for Age^2 (-0.15) viser at det er et ikke lineært forhold mellom alder og maksimalstyrke. Etter en viss alder, så vil styrken avta.</p>
<p>Alle koeffisientene har en p-verdi på &lt;0.001, som betyr at både kjønn og alder har en statistisk signifikant effekt på styrke. Modellen kan forklare omtrentlig 14% av variasjonen i total vekt løftet (Justert R-squared = 0.14), som tyder på at andre faktorer enn kjønn og alder spiller inn på maksimalstyrke.</p>
</section>
<section id="graf-2-kurvilineær-graf-av-sammenhengen-mellom-total-kjønn-og-alder" class="level3" data-number="1.2.2">
<h3 data-number="1.2.2" class="anchored" data-anchor-id="graf-2-kurvilineær-graf-av-sammenhengen-mellom-total-kjønn-og-alder"><span class="header-section-number">1.2.2</span> Graf 2: Kurvilineær graf av sammenhengen mellom total, kjønn og alder</h3>
<p><em>Graf 2: Figuren viser hvordan totalen varierer med alder for menn og kvinner, og når en topp rundt en alder av 30 -35 år, før den gradvis avtar.</em></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Arbeidskrav3_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="hvordan-kan-vi-tolke-estimatet-i-en-generalisert-lineær-modell-hvor-den-avhengige-variabelen-er-enten-1-eller-0-hva-betyr-link-function-i-denne-sammenhengen-og-hva-gjør-den" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="hvordan-kan-vi-tolke-estimatet-i-en-generalisert-lineær-modell-hvor-den-avhengige-variabelen-er-enten-1-eller-0-hva-betyr-link-function-i-denne-sammenhengen-og-hva-gjør-den"><span class="header-section-number">1.3</span> Hvordan kan vi tolke estimatet i en generalisert lineær modell hvor den avhengige variabelen er enten 1 eller 0? Hva betyr «link-function» i denne sammenhengen og hva gjør den?</h2>
<p>En generalisert lineær modell (GLM) er en type modell som lar oss jobbe med data som ikke er normalfordelt. I vårt tilfelle, så kan vi bruke en logistisk regresjonsmodell som er en underkategori av GLM, for å se på log-oddsen for et binomialt utfall, som godkjent og ikke-godkjent løft.</p>
<p>Vi tar utgangspunkt i om løfteren har fått det tredje løftet sitt i markløft godkjent eller ikke. Variabelen”Deadlift3Kg” i datasettet blir brukt for å lage vår binære utfallsvariabel “Deadlift3_success”. I openpowerlifting-datasettet, så har et godkjent løft en positiv verdi (eks: 120), og et ikke-godkjent løft en negativ verdi (eks: -120). Vi kan dermed definere utfallsvariabelen som 1 for godkjent løft hvis variabelen “Deadlift3Kg” &gt; 0, og som 0 for ikke-godkjent løft hvis “Deadlift3Kg” &lt; 0. Hvis verdien til variabelen er “NA”, betyr det at løftet ikke ble forsøkt, og disse verdiene blir ekskludert fra modellen.</p>
<p>I modellen vår blir den uavhengige variabelen absolutt vekt forsøkt i markløft (Deadlift3attempt). Vi kan anta at med økende vekt, så vil sannsynligheten for å få et godkjent løft synke. Vi vil dermed forvente en negativ koeffisient.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">1.763</td>
<td style="text-align: right;">0.008</td>
<td style="text-align: right;">220.813</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Deadlift3attempt</td>
<td style="text-align: right;">-0.006</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">-167.043</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Arbeidskrav3_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Vi får følgende estimater i modellen vår, med skjæringspunkt = 1,7 og et stigningstall = -0.006. Skjæringspunktet forteller oss log-oddsen for å få et godkjent løft når den uavhengige variabelen er 0, altså når man løfter 0 kg. Dette er i praksis absurd, og ikke nyttig. Når vi ser på stigningstallet, så ser vi at den har en negativ verdi. Det betyr at for hver økning i x (antall kg), så vil log-oddsen reduseres med 0.006. På odds-skalaen vil det bety at oddsen multipliseres med exp(-0.006) = 0.994. Med andre ord, vil oddsen for å lykkes med tredje forsøket i markløft reduseres med ca. 0.6% per kg man øker vekten med.</p>
<p><em><strong>Merk</strong>: Modellen predikerer kun basert på vekt forsøkt, og tar ikke hensyn til andre faktorer som treningserfaring, muskelmasse, teknikk og så videre.</em></p>
<p>I den logistiske regresjonsmodellen, så ønsker vi å se på sannsynligheten for et utfall ved hjelp av en lineær regresjonsmodell. Problemet med dette, er at sannsynligheten må alltid ha en verdi mellom 0 og 1, og en lineær regresjon kan gi oss verdier langt utenfor dette spennet. “Link-function” fungerer som en bro, ved at den transformerer sannsynligheter om til log-odds, som kan være verdier utenfor 0 til 1. Dermed kan vi fortsatt bruke den kraftige lineære regresjonsmodellen selv på binære utfall, ved hjelp av denne funksjonen.</p>
</section>
</section>
<section id="predikere-observasjoner" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Predikere observasjoner</h1>
<section id="bruk-data-fra-datasettet-strengthvolume-og-lag-en-prediksjonsmodell-for-legext-basert-på-legpress." class="level3" data-number="2.0.1">
<h3 data-number="2.0.1" class="anchored" data-anchor-id="bruk-data-fra-datasettet-strengthvolume-og-lag-en-prediksjonsmodell-for-legext-basert-på-legpress."><span class="header-section-number">2.0.1</span> Bruk data fra datasettet strengthvolume og lag en prediksjonsmodell for legext basert på legpress.</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Vi må først filtrere datasettet</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>Legext_modell <span class="ot">&lt;-</span> strengthvolume <span class="sc">|&gt;</span> </span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(exercise <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"legpress"</span>, <span class="st">"legext"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> exercise,</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">values_from =</span> load)</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="co">#Prediksjonsmodell for legext basert på legpress</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>ext.m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(legext <span class="sc">~</span> legpress, <span class="at">data =</span> Legext_modell)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="bruk-data-fra-et-tidspunkt-time-og-et-treningsvolum-sets" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="bruk-data-fra-et-tidspunkt-time-og-et-treningsvolum-sets"><span class="header-section-number">2.1</span> Bruk data fra et tidspunkt (time) og et treningsvolum (sets)</h2>
<section id="hvordan-spiller-kjønn-sex-inn-på-prediksjonen-hvordan-kan-du-bruke-kjønn-for-å-si-noe-om-prediksjoner-innad-kjønn-og-i-gjennomsnitt-i-begge-kjønn" class="level3" data-number="2.1.1">
<h3 data-number="2.1.1" class="anchored" data-anchor-id="hvordan-spiller-kjønn-sex-inn-på-prediksjonen-hvordan-kan-du-bruke-kjønn-for-å-si-noe-om-prediksjoner-innad-kjønn-og-i-gjennomsnitt-i-begge-kjønn"><span class="header-section-number">2.1.1</span> Hvordan spiller kjønn (sex) inn på prediksjonen, hvordan kan du bruke kjønn for å si noe om prediksjoner innad kjønn og i gjennomsnitt i begge kjønn?</h3>
<p>Vi trenger to modeller for å svare på dette spørsmålet. Den første modellen, “ext.m2” har ingen interaksjonseffekt mellom kjønn og legpress på legextension, mens “ext.m3” har en interaksjonseffekt mellom kjønn og legpress på legextension. La oss se hva modellene viser oss, og hvilken som er mest egnet.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Tabell 1: Prediksjoner fra de ulike modellene</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: right;">Prediction</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">m1 (average)</td>
<td style="text-align: right;">56.21</td>
</tr>
<tr class="even">
<td style="text-align: left;">m2 (female)</td>
<td style="text-align: right;">51.12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">m2 (male)</td>
<td style="text-align: right;">67.54</td>
</tr>
<tr class="even">
<td style="text-align: left;">m3 (female)</td>
<td style="text-align: right;">50.48</td>
</tr>
<tr class="odd">
<td style="text-align: left;">m3 (male)</td>
<td style="text-align: right;">68.64</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>I tabell 1 ser vi at m2 og m3 viser tydelige forskjeller i styrke i legextension mellom menn og kvinner. Dette er forventet, ettersom menn er i gjennomsnitt sterkere enn kvinner. Likevel, ser det ut til at m3 og m2 gir nesten nøyaktig like prediksjoner, som betyr at mest sannsynlig er ikke interaksjonseffekten særlig viktig. Vi kan dermed si at m2 er tilstrekkelig for våre behov. I modell m1, som ikke inkluderer kjønn, ser vi at vi får et gjennomsnitt som ligger mellom verdiene til menn og kvinner.</p>
</section>
<section id="modellen-gir-deg-et-estimat-men-for-en-gitt-verdi-på-legpress-hva-sier-modellen-om-i-hvilket-område-vi-kan-forvente-å-finne-nye-observasjoner" class="level3" data-number="2.1.2">
<h3 data-number="2.1.2" class="anchored" data-anchor-id="modellen-gir-deg-et-estimat-men-for-en-gitt-verdi-på-legpress-hva-sier-modellen-om-i-hvilket-område-vi-kan-forvente-å-finne-nye-observasjoner"><span class="header-section-number">2.1.2</span> Modellen gir deg et estimat, men for en gitt verdi på legpress, hva sier modellen om i hvilket område vi kan forvente å finne nye observasjoner?</h3>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Tabell 2: 95% prediksjonsintervall for legextension ved legpress = 150 kg</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Sex</th>
<th style="text-align: right;">Prediction</th>
<th style="text-align: right;">Lower</th>
<th style="text-align: right;">Upper</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Female</td>
<td style="text-align: right;">51.12</td>
<td style="text-align: right;">27.01</td>
<td style="text-align: right;">75.23</td>
</tr>
<tr class="even">
<td style="text-align: left;">Male</td>
<td style="text-align: right;">67.54</td>
<td style="text-align: right;">43.37</td>
<td style="text-align: right;">91.71</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Prediksjonsintervallet vårt forteller oss hvilke verdier vi kan forvente for legextension når en deltaker klarer 150 kg i legpress, både for kvinnelig og mannlig kjønn.</p>
<p>Hvis en kvinne tar 150kg i legpress, forventer vi at nye observasjoner forkvinner har en 95% sannsynlighet for å få en legextension verdi mellom 27 og 75kg. Modellen viser oss en gjennomsnittlig prediksjon på 51kg. Hvis en mann tar 150 kg i legpress, forventer vi at nye observasjoner for menn har en 95% sannsynlighet for å få en legextension verdi mellom 43 og 91 kg. Modellen viser oss en gjennomsnittlig prediksjon på 68 kg.</p>
<p>Prediksjonsintervaller viser oss at det er et stort spenn av mulige verdier for legextension når legpress er 150kg, for begge kjønn. Dette kan tyde på store individuelle forskjeller, selv ved samme legpress verdier.</p>
</section>
</section>
</section>
<section id="trekke-slutninger" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Trekke slutninger</h1>
<section id="bruk-datasettet-strengtvolume-og-formuler-en-modell-som-gir-oss-et-estimat-på-forskjell-i-gjennomsnitt-mellom-sets-i-forandring-fra-tidspunkt-pre-til-tidspunkt-post-i-legext.-gi-begrunnelse-til-valg-av-modell-og-håndtering-av-data." class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="bruk-datasettet-strengtvolume-og-formuler-en-modell-som-gir-oss-et-estimat-på-forskjell-i-gjennomsnitt-mellom-sets-i-forandring-fra-tidspunkt-pre-til-tidspunkt-post-i-legext.-gi-begrunnelse-til-valg-av-modell-og-håndtering-av-data."><span class="header-section-number">3.1</span> Bruk datasettet strengtvolume og formuler en modell som gir oss et estimat på forskjell i gjennomsnitt mellom sets i forandring fra tidspunkt pre til tidspunkt post i legext. Gi begrunnelse til valg av modell og håndtering av data.</h2>
<p>Trinnvis beskrivelse av oppgaveløsning:</p>
<p>Vi løser oppgaven i JASP.</p>
<p>· Vi begynte å redigere dataen og gi tallverdier. Først inkluderte vi kun “pre” og “post” i “time”, samt ga de en tallverdi 1 – 2. i “exercise” fjernet vi alle øvelser unntatt legext. · Videre gikk vi inn på linear mixed model, satte “load” som dependent variable, “sets” og “time” i fixed effects variables, og “participants” i random effects grouping factors. · Så satte vi inn “sets” og “time”, og “sets x time” inn som ulike model components · I random components valgte vi å se på intercept . · I options huket vi av model summary og fixed effects estimates. · I plots for å få selve modellen satte vi inn «time» i den horisontale aksen, «sets» i seperate lines for å skille mellom pre og post, og «participants» inn i background data show. · I tillegg førte vi inn i plots for å illustrere med en graf.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Figurer/Mixed_effect.png" class="img-fluid figure-img"></p>
<figcaption>Tabell 3: Mixed effect modellen</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Figurer/Graf.png" class="img-fluid figure-img" style="width:50.0%"></p>
<figcaption>Graf 3: Linjediagram av mixed-effect modellen. Endring i belastning fra pre- til post. Stiplet linje er single sett, og heltrukket linje er multiple sets</figcaption>
</figure>
</div>
<section id="hvordan-kan-vi-bruke-regresjonsmodellen-for-å-si-noe-om-populasjonen-som-dataene-kommer-fra" class="level3" data-number="3.1.1">
<h3 data-number="3.1.1" class="anchored" data-anchor-id="hvordan-kan-vi-bruke-regresjonsmodellen-for-å-si-noe-om-populasjonen-som-dataene-kommer-fra"><span class="header-section-number">3.1.1</span> Hvordan kan vi bruke regresjonsmodellen for å si noe om populasjonen som dataene kommer fra?</h3>
<p>Vi kan bruke regresjonsmodellen for å si noe om at det er en klar tidseffekt fra pre til post tester. Observasjonene fra modellen viser oss også forskjellen mellom økning i single og multiple sets fra pre til post på modellen ser vi at økningen er større i flere sets. Forskjellen mellom single og multiple sets på baseline er ubetydelig (p=0.809).</p>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>